# Generated by Django 4.2 on 2023-06-12 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0025_alter_employee_country"),
        ("account", "0002_profile_staff_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="head_of_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="head_of_department",
                to="staff.employee",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="immediate_supervisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="immediate_supervisor",
                to="staff.employee",
            ),
        ),
    ]
