# Generated by Django 4.2 on 2023-06-15 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_profile_is_hod_profile_is_supervisor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="head_of_department",
        ),
    ]
