# Generated by Django 4.2 on 2023-06-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_remove_profile_head_of_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_hr",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
