# Generated by Django 4.2 on 2023-04-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_name", models.CharField(max_length=50)),
                ("nickname", models.CharField(blank=True, max_length=50, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "place_of_birth",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "gender",
                    models.CharField(choices=[("F", "F"), ("M", "M")], max_length=2),
                ),
                ("nationality", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("Single", "Single"),
                            ("Married", "Married"),
                            ("Widowed", "Widowed"),
                            ("Divorced", "Divorced"),
                        ],
                        max_length=50,
                    ),
                ),
                ("spouse", models.CharField(blank=True, max_length=50, null=True)),
                ("national_id", models.BigIntegerField(blank=True, null=True)),
                ("passport", models.CharField(max_length=6)),
                ("drivers_license", models.CharField(max_length=10)),
                ("voters_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "account_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "bank",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Yonna Islamic Microfinance", "Yonna Islamic Microfinance")
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("swift_code", models.CharField(blank=True, max_length=100, null=True)),
                ("account_number", models.BigIntegerField(blank=True, null=True)),
                (
                    "country",
                    models.CharField(blank=True, choices=[], max_length=100, null=True),
                ),
                ("street", models.CharField(blank=True, max_length=50, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("zip_code", models.IntegerField()),
                ("cug_number", models.CharField(blank=True, max_length=12, null=True)),
                ("mobile_1", models.CharField(blank=True, max_length=12, null=True)),
                ("mobile_2", models.CharField(blank=True, max_length=12, null=True)),
                (
                    "personal_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "work_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("hired_date", models.DateField()),
                ("resigned_date", models.DateField(blank=True, null=True)),
                ("contract_commence", models.DateField(blank=True, null=True)),
                ("contract_end", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
