# Generated by Django 4.2 on 2023-04-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0005_employee_classification_employee_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="emp_status",
            field=models.CharField(
                choices=[
                    ("Full Time", "Full Time"),
                    ("Part Time", "Part Time"),
                    ("Temporary", "Temporary"),
                    ("Contract", "Contract"),
                    ("Independent Contract", "Independent Contract"),
                    ("Intern", "Intern"),
                    ("Attachment", "Attachment"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="probation",
            field=models.BooleanField(default=True),
        ),
    ]
