# Generated by Django 4.2 on 2023-04-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0008_alter_employee_emp_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="probation",
        ),
        migrations.AddField(
            model_name="employee",
            name="probation_commence",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="probation_end",
            field=models.DateField(blank=True, null=True),
        ),
    ]
