# Generated by Django 4.2 on 2023-04-14 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0009_remove_employee_probation_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="emp_status",
            new_name="employment_status",
        ),
    ]
