# Generated by Django 4.2 on 2023-04-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0010_rename_emp_status_employee_employment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="image",
            field=models.ImageField(
                default="profile_pics/default.png", upload_to="profile_pics"
            ),
        ),
    ]
