# Generated by Django 4.2 on 2023-04-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0011_employee_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="national_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
