# Generated by Django 4.2 on 2023-04-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0012_alter_employee_national_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="national_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
