# Generated by Django 4.2 on 2023-04-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0013_alter_employee_national_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employment_status",
            field=models.CharField(
                choices=[
                    ("Attachment", "Attachment"),
                    ("Contract", "Contract"),
                    ("Fired", "Fired"),
                    ("Full Time", "Full Time"),
                    ("Independent Contract", "Independent Contract"),
                    ("Intern", "Intern"),
                    ("On Leave", "On Leave"),
                    ("On Suspension", "On Suspension"),
                    ("Part Time", "Part Time"),
                    ("Resigned", "Resigned"),
                    ("Temporary", "Temporary"),
                ],
                max_length=50,
            ),
        ),
    ]
