# Generated by Django 4.2 on 2023-04-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0014_alter_employee_employment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="sshfc",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="staff_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="tin",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employment_status",
            field=models.CharField(
                choices=[
                    ("Attachment", "Attachment"),
                    ("Contract", "Contract"),
                    ("Fired", "Fired"),
                    ("Full Time", "Full Time"),
                    ("Independent Contract", "Independent Contract"),
                    ("Intern", "Intern"),
                    ("On Leave", "On Leave"),
                    ("On Suspension", "On Suspension"),
                    ("Part Time", "Part Time"),
                    ("Probation", "Probation"),
                    ("Resigned", "Resigned"),
                    ("Temporary", "Temporary"),
                ],
                max_length=50,
            ),
        ),
    ]
