# Generated by Django 4.2 on 2023-04-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0015_employee_sshfc_employee_staff_id_employee_tin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="warning",
            field=models.IntegerField(default=0),
        ),
    ]
