# Generated by Django 4.2 on 2023-04-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0017_employee_facebook_link_employee_instagram_link_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="employee",
            name="skills",
            field=models.ManyToManyField(blank=True, null=True, to="staff.skill"),
        ),
    ]
