# Generated by Django 4.2 on 2023-04-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0018_skill_employee_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="skills",
            field=models.ManyToManyField(to="staff.skill"),
        ),
    ]
