# Generated by Django 4.2 on 2023-04-20 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0019_alter_employee_skills"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="division",
        ),
    ]
