# Generated by Django 4.2 on 2023-04-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0020_remove_employee_division"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="country",
            field=models.CharField(blank=True, choices=[], max_length=100, null=True),
        ),
    ]
