# Generated by Django 4.2 on 2023-05-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0022_alter_employee_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="suspensions",
            field=models.IntegerField(default=0),
        ),
    ]
