# Generated by Django 4.2 on 2023-06-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "staff",
            "0027_rename_total_days_of_leave_employee_total_annual_leave_days_taken_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="total_days_of_leave_taken",
            field=models.IntegerField(default=0),
        ),
    ]
