# Generated by Django 4.2 on 2023-04-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payroll",
            name="basic_salary",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="gross_pay",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="housing_allowance",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="income_tax",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="individual_sshfc",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="medical_allowance",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="net_pay",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="responsibility_allowance",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="sshfc",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="transport_allowance",
            field=models.FloatField(default=0.0),
        ),
    ]
