# Generated by Django 4.2 on 2023-04-26 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0002_alter_payroll_basic_salary_alter_payroll_gross_pay_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payroll",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
