# Generated by Django 4.2 on 2023-04-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0005_payroll_staff_fin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payroll",
            name="comment",
        ),
        migrations.AddField(
            model_name="payroll",
            name="deduction_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
