# Generated by Django 4.2 on 2023-06-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0008_alter_payroll_income_tax"),
    ]

    operations = [
        migrations.AddField(
            model_name="payroll",
            name="risk_allowance",
            field=models.FloatField(default=0.0),
        ),
    ]
