# Generated by Django 4.2 on 2023-11-09 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_payroll_risk_allowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='refund',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
