# Generated by Django 5.2.4 on 2025-08-01 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_payroll_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='ninety_percent_net',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='provincial_allowance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='ten_percent_net',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='total_deduction',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
