# Generated by Django 4.2 on 2023-05-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave_roster", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaveroster",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="leaveroster",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leaveroster",
            name="home_tel",
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name="leaveroster",
            name="leave_reason",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="leaveroster",
            name="mobile_tel",
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name="leaveroster",
            name="number_of_days",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="leaveroster",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leaveroster",
            name="type_of_leave",
            field=models.CharField(
                choices=[
                    ("Annual", "Annual"),
                    ("Maternity", "Maternity"),
                    ("Sick", "Sick"),
                    ("Compassionate", "Compassionate"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
