# Generated by Django 4.2 on 2023-05-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave_roster", "0003_alter_leaveroster_home_tel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaveroster",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
