# Generated by Django 4.2 on 2023-06-07 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leave_roster", "0004_leaveroster_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leaveroster",
            old_name="home_tel",
            new_name="phone_number",
        ),
        migrations.RemoveField(
            model_name="leaveroster",
            name="mobile_tel",
        ),
    ]
