# Generated by Django 4.2 on 2023-06-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave_roster", "0005_rename_home_tel_leaveroster_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaveroster",
            name="email",
            field=models.EmailField(default="", max_length=254),
            preserve_default=False,
        ),
    ]
