# Generated by Django 4.2 on 2023-06-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave_roster", "0006_alter_leaveroster_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaveroster",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="leaveroster",
            name="status",
            field=models.TextField(
                choices=[
                    ("Immediate Supervision", "Immediate Supervision"),
                    ("Head Of Department", "Head Of Department"),
                    ("Rejected", "Rejected"),
                    ("Approved", "Approved"),
                    ("Pending", "Pending"),
                ]
            ),
        ),
    ]
