# Generated by Django 4.2 on 2023-06-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave_roster", "0007_leaveroster_approved_alter_leaveroster_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leaveroster",
            name="email",
        ),
        migrations.RemoveField(
            model_name="leaveroster",
            name="phone_number",
        ),
        migrations.AlterField(
            model_name="leaveroster",
            name="status",
            field=models.TextField(
                choices=[
                    ("Immediate Supervisor", "Immediate Supervisor"),
                    ("Head Of Department", "Head Of Department"),
                    ("Rejected", "Rejected"),
                    ("Approved", "Approved"),
                    ("Pending", "Pending"),
                ]
            ),
        ),
    ]
