# Generated by Django 4.2 on 2023-07-14 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0028_alter_employee_total_days_of_leave_taken"),
        ("leave_roster", "0011_alter_leaveroster_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaveroster",
            name="_staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="staff.employee",
            ),
        ),
    ]
