# Generated by Django 4.2 on 2023-07-14 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leave_roster", "0012_leaveroster__staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leaveroster",
            name="staff",
        ),
    ]
