# Generated by Django 4.2 on 2023-07-14 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leave_roster", "0013_remove_leaveroster_staff"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leaveroster",
            old_name="_staff",
            new_name="staff",
        ),
    ]
