# Generated by Django 4.2 on 2023-07-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave_roster", "0014_rename__staff_leaveroster_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leaveroster",
            name="approved",
        ),
        migrations.AlterField(
            model_name="leaveroster",
            name="status",
            field=models.TextField(
                blank=True, choices=[("Approved", "Approved")], null=True
            ),
        ),
    ]
