# Generated by Django 4.2 on 2023-07-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave_roster", "0015_remove_leaveroster_approved_alter_leaveroster_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaveroster",
            name="type_of_leave",
            field=models.CharField(
                choices=[
                    ("Annual", "Annual"),
                    ("Maternity", "Maternity"),
                    ("Paternity", "Paternity"),
                    ("Sick", "Sick"),
                    ("Compassionate", "Compassionate"),
                ],
                max_length=50,
            ),
        ),
    ]
